### ISSUE TITLE
Allowing attributes and resources to take interface type instead of string

### ISSUE THREAD

**Issue by AJ-54** [open-telemetry/opentelemetry-log-collection#213] opened 2021-07-08 04:27 UTC
The `entry.go`  file [here](https://github.com/open-telemetry/opentelemetry-log-collection/blob/baea74bc95f4e44832ed749f4b436c501417b5a9/entry/entry.go#L47) should allow attributes to be of type interface and not string, string restricts the value to be string ONLY but we know that we can actually have attributes that can take a map structure as value too.

**Comment by djaglowski** [comment] 2021-07-08 14:22
Duplicate of #190

**Closed by djaglowski** 2021-07-08 14:22 UTC
